import { PDFDocument, StandardFonts, rgb } from 'pdf-lib'
import { formatHours } from '~/lib/hours'

export type CertificateData = {
  orgName: string
  orgContactEmail: string
  memberName: string
  scope: 'award' | 'summary'
  totalMinutes: number
  periodStart: string | null
  periodEnd: string | null
  activity: string | null
  verificationId: string
  verifyUrl: string
  issuedAt: Date
  issuedByName: string
}

const PAGE_WIDTH = 612
const PAGE_HEIGHT = 792
const MARGIN = 56

const INK = rgb(0.06, 0.09, 0.16)
const MUTED = rgb(0.39, 0.45, 0.55)
const ACCENT = rgb(0.31, 0.27, 0.9)
const RULE = rgb(0.85, 0.88, 0.93)

function formatDate(value: Date): string {
  return value.toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    timeZone: 'UTC',
  })
}

function formatIsoDate(value: string): string {
  return formatDate(new Date(`${value}T00:00:00Z`))
}

/**
 * Produces the document a member hands to their school. Everything a verifier
 * needs is on the page, including the id they can check independently.
 */
export async function renderCertificatePdf(
  data: CertificateData,
): Promise<Uint8Array> {
  const pdf = await PDFDocument.create()
  pdf.setTitle(`Volunteer hours verification ${data.verificationId}`)
  pdf.setAuthor(data.orgName)
  pdf.setSubject('Verification of volunteer service hours')
  pdf.setProducer(data.orgName)

  const page = pdf.addPage([PAGE_WIDTH, PAGE_HEIGHT])
  const regular = await pdf.embedFont(StandardFonts.Helvetica)
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold)

  let y = PAGE_HEIGHT - MARGIN

  const text = (
    value: string,
    options: { size: number; font?: typeof regular; color?: typeof INK; x?: number },
  ) => {
    page.drawText(value, {
      x: options.x ?? MARGIN,
      y,
      size: options.size,
      font: options.font ?? regular,
      color: options.color ?? INK,
    })
  }

  page.drawRectangle({
    x: 0,
    y: PAGE_HEIGHT - 8,
    width: PAGE_WIDTH,
    height: 8,
    color: ACCENT,
  })

  y -= 12
  text(data.orgName.toUpperCase(), { size: 11, font: bold, color: MUTED })

  y -= 38
  text('Verification of Volunteer Hours', { size: 24, font: bold })

  y -= 26
  text(
    data.scope === 'award'
      ? 'This certifies a single approved volunteer service entry.'
      : "This certifies the member's complete approved volunteer service record.",
    { size: 11, color: MUTED },
  )

  y -= 34
  page.drawLine({
    start: { x: MARGIN, y },
    end: { x: PAGE_WIDTH - MARGIN, y },
    thickness: 1,
    color: RULE,
  })

  y -= 34
  text('VOLUNTEER', { size: 9, font: bold, color: MUTED })
  y -= 20
  text(data.memberName, { size: 18, font: bold })

  y -= 40
  text('TOTAL APPROVED HOURS', { size: 9, font: bold, color: MUTED })
  y -= 26
  text(formatHours(data.totalMinutes), { size: 32, font: bold, color: ACCENT })

  const rows: Array<[string, string]> = []

  if (data.scope === 'award' && data.activity) {
    rows.push(['Activity', data.activity])
  }
  if (data.periodStart && data.periodEnd) {
    rows.push([
      data.scope === 'award' ? 'Service date' : 'Service period',
      data.periodStart === data.periodEnd
        ? formatIsoDate(data.periodStart)
        : `${formatIsoDate(data.periodStart)} to ${formatIsoDate(data.periodEnd)}`,
    ])
  }
  rows.push(['Issued on', formatDate(data.issuedAt)])
  rows.push(['Issued by', data.issuedByName])
  if (data.orgContactEmail) rows.push(['Organization contact', data.orgContactEmail])

  y -= 44
  for (const [label, value] of rows) {
    text(label, { size: 10, font: bold, color: MUTED })
    const wrapped = wrapText(value, regular, 11, PAGE_WIDTH - MARGIN * 2 - 150)
    let lineY = y
    for (const line of wrapped) {
      page.drawText(line, {
        x: MARGIN + 150,
        y: lineY,
        size: 11,
        font: regular,
        color: INK,
      })
      lineY -= 15
    }
    y = Math.min(y - 24, lineY - 9)
  }

  y -= 10
  page.drawLine({
    start: { x: MARGIN, y },
    end: { x: PAGE_WIDTH - MARGIN, y },
    thickness: 1,
    color: RULE,
  })

  y -= 30
  text('VERIFICATION ID', { size: 9, font: bold, color: MUTED })
  y -= 22
  text(data.verificationId, { size: 16, font: bold })

  y -= 28
  for (const line of wrapText(
    `Anyone can confirm this document is genuine, and see the member's current approved total, at ${data.verifyUrl}`,
    regular,
    10,
    PAGE_WIDTH - MARGIN * 2,
  )) {
    text(line, { size: 10, color: MUTED })
    y -= 14
  }

  page.drawText(
    `Generated by ${data.orgName} volunteer hours system on ${formatDate(data.issuedAt)}.`,
    {
      x: MARGIN,
      y: MARGIN - 16,
      size: 8,
      font: regular,
      color: MUTED,
    },
  )

  return pdf.save()
}

function wrapText(
  value: string,
  font: Awaited<ReturnType<PDFDocument['embedFont']>>,
  size: number,
  maxWidth: number,
): Array<string> {
  const words = value.split(/\s+/).filter(Boolean)
  const lines: Array<string> = []
  let current = ''

  for (const word of words) {
    const candidate = current ? `${current} ${word}` : word
    if (font.widthOfTextAtSize(candidate, size) <= maxWidth) {
      current = candidate
    } else {
      if (current) lines.push(current)
      current = word
    }
  }
  if (current) lines.push(current)
  return lines.length > 0 ? lines : ['']
}
