/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppOnboardingRouteImport } from './routes/_app/onboarding'
import { Route as AppPendingRouteImport } from './routes/_app/pending'
import { Route as AppRegisterRouteImport } from './routes/_app/register'
import { Route as AppSuspendedRouteImport } from './routes/_app/suspended'
import { Route as VerifyVerificationIdRouteImport } from './routes/verify.$verificationId'
import { Route as AppAdminIndexRouteImport } from './routes/_app/admin/index'
import { Route as AppAdminAuditRouteImport } from './routes/_app/admin/audit'
import { Route as AppAdminPeopleRouteImport } from './routes/_app/admin/people'
import { Route as AppAdminRolesRouteImport } from './routes/_app/admin/roles'
import { Route as AppRequestsRequestIdRouteImport } from './routes/_app/requests.$requestId'
import { Route as AppRequestsNewRouteImport } from './routes/_app/requests.new'
import { Route as ApiAttachmentsAttachmentIdRouteImport } from './routes/api/attachments/$attachmentId'
import { Route as ApiCertificatesCertificateIdRouteImport } from './routes/api/certificates/$certificateId'
import { Route as AppAdminRequestsRequestIdRouteImport } from './routes/_app/admin/requests.$requestId'
import { Route as ApiAuthGoogleCallbackRouteImport } from './routes/api/auth/google/callback'
import { Route as ApiAuthGoogleStartRouteImport } from './routes/api/auth/google/start'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppPendingRoute = AppPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => AppRoute,
} as any)
const AppRegisterRoute = AppRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AppRoute,
} as any)
const AppSuspendedRoute = AppSuspendedRouteImport.update({
  id: '/suspended',
  path: '/suspended',
  getParentRoute: () => AppRoute,
} as any)
const VerifyVerificationIdRoute = VerifyVerificationIdRouteImport.update({
  id: '/verify/$verificationId',
  path: '/verify/$verificationId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminAuditRoute = AppAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminPeopleRoute = AppAdminPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminRolesRoute = AppAdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppRequestsRequestIdRoute = AppRequestsRequestIdRouteImport.update({
  id: '/requests/$requestId',
  path: '/requests/$requestId',
  getParentRoute: () => AppRoute,
} as any)
const AppRequestsNewRoute = AppRequestsNewRouteImport.update({
  id: '/requests/new',
  path: '/requests/new',
  getParentRoute: () => AppRoute,
} as any)
const ApiAttachmentsAttachmentIdRoute =
  ApiAttachmentsAttachmentIdRouteImport.update({
    id: '/api/attachments/$attachmentId',
    path: '/api/attachments/$attachmentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCertificatesCertificateIdRoute =
  ApiCertificatesCertificateIdRouteImport.update({
    id: '/api/certificates/$certificateId',
    path: '/api/certificates/$certificateId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppAdminRequestsRequestIdRoute =
  AppAdminRequestsRequestIdRouteImport.update({
    id: '/requests/$requestId',
    path: '/requests/$requestId',
    getParentRoute: () => AppAdminRoute,
  } as any)
const ApiAuthGoogleCallbackRoute = ApiAuthGoogleCallbackRouteImport.update({
  id: '/api/auth/google/callback',
  path: '/api/auth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGoogleStartRoute = ApiAuthGoogleStartRouteImport.update({
  id: '/api/auth/google/start',
  path: '/api/auth/google/start',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/onboarding': typeof AppOnboardingRoute
  '/pending': typeof AppPendingRoute
  '/register': typeof AppRegisterRoute
  '/suspended': typeof AppSuspendedRoute
  '/verify/$verificationId': typeof VerifyVerificationIdRoute
  '/admin/audit': typeof AppAdminAuditRoute
  '/admin/people': typeof AppAdminPeopleRoute
  '/admin/roles': typeof AppAdminRolesRoute
  '/requests/$requestId': typeof AppRequestsRequestIdRoute
  '/requests/new': typeof AppRequestsNewRoute
  '/api/attachments/$attachmentId': typeof ApiAttachmentsAttachmentIdRoute
  '/api/certificates/$certificateId': typeof ApiCertificatesCertificateIdRoute
  '/admin/': typeof AppAdminIndexRoute
  '/admin/requests/$requestId': typeof AppAdminRequestsRequestIdRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
  '/api/auth/google/start': typeof ApiAuthGoogleStartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/onboarding': typeof AppOnboardingRoute
  '/pending': typeof AppPendingRoute
  '/register': typeof AppRegisterRoute
  '/suspended': typeof AppSuspendedRoute
  '/verify/$verificationId': typeof VerifyVerificationIdRoute
  '/admin/audit': typeof AppAdminAuditRoute
  '/admin/people': typeof AppAdminPeopleRoute
  '/admin/roles': typeof AppAdminRolesRoute
  '/requests/$requestId': typeof AppRequestsRequestIdRoute
  '/requests/new': typeof AppRequestsNewRoute
  '/api/attachments/$attachmentId': typeof ApiAttachmentsAttachmentIdRoute
  '/api/certificates/$certificateId': typeof ApiCertificatesCertificateIdRoute
  '/admin': typeof AppAdminIndexRoute
  '/admin/requests/$requestId': typeof AppAdminRequestsRequestIdRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
  '/api/auth/google/start': typeof ApiAuthGoogleStartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/onboarding': typeof AppOnboardingRoute
  '/_app/pending': typeof AppPendingRoute
  '/_app/register': typeof AppRegisterRoute
  '/_app/suspended': typeof AppSuspendedRoute
  '/verify/$verificationId': typeof VerifyVerificationIdRoute
  '/_app/admin/audit': typeof AppAdminAuditRoute
  '/_app/admin/people': typeof AppAdminPeopleRoute
  '/_app/admin/roles': typeof AppAdminRolesRoute
  '/_app/requests/$requestId': typeof AppRequestsRequestIdRoute
  '/_app/requests/new': typeof AppRequestsNewRoute
  '/api/attachments/$attachmentId': typeof ApiAttachmentsAttachmentIdRoute
  '/api/certificates/$certificateId': typeof ApiCertificatesCertificateIdRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_app/admin/requests/$requestId': typeof AppAdminRequestsRequestIdRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
  '/api/auth/google/start': typeof ApiAuthGoogleStartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/onboarding'
    | '/pending'
    | '/register'
    | '/suspended'
    | '/verify/$verificationId'
    | '/admin/audit'
    | '/admin/people'
    | '/admin/roles'
    | '/requests/$requestId'
    | '/requests/new'
    | '/api/attachments/$attachmentId'
    | '/api/certificates/$certificateId'
    | '/admin/'
    | '/admin/requests/$requestId'
    | '/api/auth/google/callback'
    | '/api/auth/google/start'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/onboarding'
    | '/pending'
    | '/register'
    | '/suspended'
    | '/verify/$verificationId'
    | '/admin/audit'
    | '/admin/people'
    | '/admin/roles'
    | '/requests/$requestId'
    | '/requests/new'
    | '/api/attachments/$attachmentId'
    | '/api/certificates/$certificateId'
    | '/admin'
    | '/admin/requests/$requestId'
    | '/api/auth/google/callback'
    | '/api/auth/google/start'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/admin'
    | '/_app/dashboard'
    | '/_app/onboarding'
    | '/_app/pending'
    | '/_app/register'
    | '/_app/suspended'
    | '/verify/$verificationId'
    | '/_app/admin/audit'
    | '/_app/admin/people'
    | '/_app/admin/roles'
    | '/_app/requests/$requestId'
    | '/_app/requests/new'
    | '/api/attachments/$attachmentId'
    | '/api/certificates/$certificateId'
    | '/_app/admin/'
    | '/_app/admin/requests/$requestId'
    | '/api/auth/google/callback'
    | '/api/auth/google/start'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  VerifyVerificationIdRoute: typeof VerifyVerificationIdRoute
  ApiAttachmentsAttachmentIdRoute: typeof ApiAttachmentsAttachmentIdRoute
  ApiCertificatesCertificateIdRoute: typeof ApiCertificatesCertificateIdRoute
  ApiAuthGoogleCallbackRoute: typeof ApiAuthGoogleCallbackRoute
  ApiAuthGoogleStartRoute: typeof ApiAuthGoogleStartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/onboarding': {
      id: '/_app/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pending': {
      id: '/_app/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof AppPendingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/register': {
      id: '/_app/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AppRegisterRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/suspended': {
      id: '/_app/suspended'
      path: '/suspended'
      fullPath: '/suspended'
      preLoaderRoute: typeof AppSuspendedRouteImport
      parentRoute: typeof AppRoute
    }
    '/verify/$verificationId': {
      id: '/verify/$verificationId'
      path: '/verify/$verificationId'
      fullPath: '/verify/$verificationId'
      preLoaderRoute: typeof VerifyVerificationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/audit': {
      id: '/_app/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AppAdminAuditRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/people': {
      id: '/_app/admin/people'
      path: '/people'
      fullPath: '/admin/people'
      preLoaderRoute: typeof AppAdminPeopleRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/roles': {
      id: '/_app/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AppAdminRolesRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/requests/$requestId': {
      id: '/_app/requests/$requestId'
      path: '/requests/$requestId'
      fullPath: '/requests/$requestId'
      preLoaderRoute: typeof AppRequestsRequestIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/requests/new': {
      id: '/_app/requests/new'
      path: '/requests/new'
      fullPath: '/requests/new'
      preLoaderRoute: typeof AppRequestsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/attachments/$attachmentId': {
      id: '/api/attachments/$attachmentId'
      path: '/api/attachments/$attachmentId'
      fullPath: '/api/attachments/$attachmentId'
      preLoaderRoute: typeof ApiAttachmentsAttachmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/certificates/$certificateId': {
      id: '/api/certificates/$certificateId'
      path: '/api/certificates/$certificateId'
      fullPath: '/api/certificates/$certificateId'
      preLoaderRoute: typeof ApiCertificatesCertificateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/admin/requests/$requestId': {
      id: '/_app/admin/requests/$requestId'
      path: '/requests/$requestId'
      fullPath: '/admin/requests/$requestId'
      preLoaderRoute: typeof AppAdminRequestsRequestIdRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/api/auth/google/callback': {
      id: '/api/auth/google/callback'
      path: '/api/auth/google/callback'
      fullPath: '/api/auth/google/callback'
      preLoaderRoute: typeof ApiAuthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/google/start': {
      id: '/api/auth/google/start'
      path: '/api/auth/google/start'
      fullPath: '/api/auth/google/start'
      preLoaderRoute: typeof ApiAuthGoogleStartRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminAuditRoute: typeof AppAdminAuditRoute
  AppAdminPeopleRoute: typeof AppAdminPeopleRoute
  AppAdminRolesRoute: typeof AppAdminRolesRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
  AppAdminRequestsRequestIdRoute: typeof AppAdminRequestsRequestIdRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminAuditRoute: AppAdminAuditRoute,
  AppAdminPeopleRoute: AppAdminPeopleRoute,
  AppAdminRolesRoute: AppAdminRolesRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
  AppAdminRequestsRequestIdRoute: AppAdminRequestsRequestIdRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppPendingRoute: typeof AppPendingRoute
  AppRegisterRoute: typeof AppRegisterRoute
  AppSuspendedRoute: typeof AppSuspendedRoute
  AppRequestsRequestIdRoute: typeof AppRequestsRequestIdRoute
  AppRequestsNewRoute: typeof AppRequestsNewRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppPendingRoute: AppPendingRoute,
  AppRegisterRoute: AppRegisterRoute,
  AppSuspendedRoute: AppSuspendedRoute,
  AppRequestsRequestIdRoute: AppRequestsRequestIdRoute,
  AppRequestsNewRoute: AppRequestsNewRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  VerifyVerificationIdRoute: VerifyVerificationIdRoute,
  ApiAttachmentsAttachmentIdRoute: ApiAttachmentsAttachmentIdRoute,
  ApiCertificatesCertificateIdRoute: ApiCertificatesCertificateIdRoute,
  ApiAuthGoogleCallbackRoute: ApiAuthGoogleCallbackRoute,
  ApiAuthGoogleStartRoute: ApiAuthGoogleStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
